2021-09-22 16:55:20,344 INFO    MainThread:362756 [wandb_setup.py:_flush():69] setting env: {}
2021-09-22 16:55:20,344 INFO    MainThread:362756 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-22 16:55:20,345 INFO    MainThread:362756 [wandb_init.py:_log_setup():342] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Chest-X-ray-Images/wandb/run-20210922_165520-1gg67fdx/logs/debug.log
2021-09-22 16:55:20,345 INFO    MainThread:362756 [wandb_init.py:_log_setup():343] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Chest-X-ray-Images/wandb/run-20210922_165520-1gg67fdx/logs/debug-internal.log
2021-09-22 16:55:20,345 INFO    MainThread:362756 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f43fc70f210>
2021-09-22 16:55:20,346 INFO    MainThread:362756 [wandb_init.py:init():375] calling init triggers
2021-09-22 16:55:20,346 INFO    MainThread:362756 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-09-22 16:55:20,346 INFO    MainThread:362756 [wandb_init.py:init():397] re-initializing run, found existing run on stack: 27w2jrhk
2021-09-22 16:55:20,347 INFO    MainThread:362756 [wandb_run.py:finish():1271] finishing run ranuga-d/Chest-X-ray-Images/27w2jrhk
2021-09-22 16:55:20,348 INFO    MainThread:362756 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 0
2021-09-22 16:55:20,348 INFO    MainThread:362756 [wandb_run.py:_restore():1543] restore
2021-09-22 16:55:21,090 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 718
}

2021-09-22 16:55:21,198 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 718
}

2021-09-22 16:55:26,299 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: None
2021-09-22 16:55:27,227 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 718
}

2021-09-22 16:55:27,582 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24796
}

2021-09-22 16:55:27,685 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24796
}

2021-09-22 16:55:27,786 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24796
}

2021-09-22 16:55:27,888 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24796
}

2021-09-22 16:55:27,989 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24796
}

2021-09-22 16:55:28,091 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24796
}

2021-09-22 16:55:28,192 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24796
}

2021-09-22 16:55:28,294 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24796
}

2021-09-22 16:55:28,395 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24796
}

2021-09-22 16:55:28,497 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24796
}

2021-09-22 16:55:28,598 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24796
}

2021-09-22 16:55:28,699 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24796
}

2021-09-22 16:55:28,801 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24796
}

2021-09-22 16:55:28,903 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24796
}

2021-09-22 16:55:29,004 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24796
}

2021-09-22 16:55:29,105 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24451
  total_bytes: 24796
}

2021-09-22 16:55:29,208 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24796
  total_bytes: 24796
}

2021-09-22 16:55:29,310 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24796
  total_bytes: 24796
}

2021-09-22 16:55:29,411 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24796
  total_bytes: 24796
}

2021-09-22 16:55:29,513 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24796
  total_bytes: 24796
}

2021-09-22 16:55:29,614 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24796
  total_bytes: 24796
}

2021-09-22 16:55:29,716 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24796
  total_bytes: 24796
}

2021-09-22 16:55:29,817 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24796
  total_bytes: 24796
}

2021-09-22 16:55:29,918 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24796
  total_bytes: 24796
}

2021-09-22 16:55:30,020 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24796
  total_bytes: 24796
}

2021-09-22 16:55:31,052 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24796
  total_bytes: 24796
}

2021-09-22 16:55:31,154 INFO    MainThread:362756 [wandb_run.py:_wait_for_finish():1693] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24796
  total_bytes: 24796
}

2021-09-22 16:55:32,256 INFO    MainThread:362756 [wandb_run.py:_show_files():1915] logging synced files
2021-09-22 16:55:32,261 INFO    MainThread:362756 [wandb_init.py:init():424] starting backend
2021-09-22 16:55:32,262 INFO    MainThread:362756 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-22 16:55:32,263 INFO    MainThread:362756 [backend.py:ensure_launched():135] starting backend process...
2021-09-22 16:55:32,315 INFO    MainThread:362756 [backend.py:ensure_launched():140] started backend process with pid: 367464
2021-09-22 16:55:32,316 INFO    MainThread:362756 [wandb_init.py:init():429] backend started and connected
2021-09-22 16:55:32,328 INFO    MainThread:362756 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-09-22 16:55:32,328 INFO    MainThread:362756 [wandb_init.py:init():477] updated telemetry
2021-09-22 16:55:32,329 INFO    MainThread:362756 [wandb_init.py:init():500] communicating current version
2021-09-22 16:55:33,150 INFO    MainThread:362756 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-09-22 16:55:33,151 INFO    MainThread:362756 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-09-22 16:55:33,572 INFO    MainThread:362756 [wandb_init.py:init():540] starting run threads in backend
2021-09-22 16:55:38,578 INFO    MainThread:362756 [wandb_run.py:_console_start():1601] atexit reg
2021-09-22 16:55:38,580 INFO    MainThread:362756 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2021-09-22 16:55:38,581 INFO    MainThread:362756 [wandb_run.py:_redirect():1512] Wrapping output streams.
2021-09-22 16:55:38,581 INFO    MainThread:362756 [wandb_run.py:_redirect():1536] Redirects installed.
2021-09-22 16:55:38,581 INFO    MainThread:362756 [wandb_init.py:init():565] run started, returning control to user process
2021-09-22 16:55:38,631 INFO    MainThread:362756 [wandb_init.py:_pause_backend():256] pausing backend
2021-09-22 16:55:38,632 INFO    MainThread:362756 [jupyter.py:save_ipynb():301] looking for notebook: 00.ipynb
2021-09-22 16:55:39,043 INFO    MainThread:362756 [wandb_init.py:_pause_backend():260] saved code: <wandb.sdk.wandb_artifacts.Artifact object at 0x7f43fc5d2a10>
2021-09-22 16:55:50,540 INFO    MainThread:362756 [wandb_init.py:_resume_backend():265] resuming backend
2021-09-22 16:55:50,550 INFO    MainThread:362756 [wandb_setup.py:_flush():69] setting env: {}
2021-09-22 16:55:50,550 INFO    MainThread:362756 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-22 16:55:50,550 INFO    MainThread:362756 [wandb_init.py:_log_setup():342] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Chest-X-ray-Images/wandb/run-20210922_165550-1jzlmw97/logs/debug.log
2021-09-22 16:55:50,550 INFO    MainThread:362756 [wandb_init.py:_log_setup():343] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Chest-X-ray-Images/wandb/run-20210922_165550-1jzlmw97/logs/debug-internal.log
2021-09-22 16:55:50,551 INFO    MainThread:362756 [wandb_init.py:init():375] calling init triggers
2021-09-22 16:55:50,551 INFO    MainThread:362756 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-09-22 16:55:50,551 INFO    MainThread:362756 [wandb_init.py:init():397] re-initializing run, found existing run on stack: 1gg67fdx
2021-09-22 16:55:50,553 INFO    MainThread:362756 [wandb_run.py:finish():1271] finishing run ranuga-d/Chest-X-ray-Images/1gg67fdx
